project:
  type: book
  output-dir: docs

number-depth: 2

book:
  title: "COMP/STAT212 Portfolio"
  author: "Your Name Here"
  date: today
  date-format: full
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  cookie-consent:
    type: implied
    style: simple

  sidebar:
    title: "Your Name Here"
    logo: assets/sidebar-logo.png
    logo-alt: "Random negative space illustration"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true

  chapters:
    - text: "Welcome"
      href: index.qmd

    - part: "Prof Viz"
      chapters:
      - src/pv/pv-01.qmd

    - part: "TidyTuesday"
      chapters:
      - src/tt/2025-07-08.qmd
      - src/tt/2025-07-15.qmd

    - part: "In-Class Activities"
      chapters:
      - src/ica/ica-sample1.qmd
      - src/ica/ica-sample2.qmd
      - src/ica/cleaning.qmd
      - src/ica/03-adv-ggplot-notes.qmd
      - src/ica/07-wrangling-2-notes.qmd

  appendices:
  - src/appx/appx-sample1.qmd
  - src/appx/appx-sample2.qmd
  - mm/mm.md

format:
  html:
    theme:
      light: flatly
      dark: darkly
    search: true
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    fontsize: 1em
    smooth-scroll: true
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    page-layout: full
    code-fold: true
    number-sections: false
    toc-expand: true

execute:
  echo: true
  warning: false
  error: false
  cache: false

editor:
  mode: source
  markdown:
    wrap: sentence
